defaults:
  - _self_
  - override hydra/launcher:  local
  - override hydra/output:  local

# snapshot
save_snapshot: false
load_snap: ""

# replay buffer
num_workers: 16
batch_size: 16 
train_steps: 200001
eval_freq: 20000
task_type: "nav"
max_dist: 100

# misc
seed: 1
device: cuda

# experiment
experiment: train_vip_nav
wandbuser: 
wandbproject: 

# data
dataset: "hm3"
root: ${oc.env:TMPDIR}
datapath: ${root}/dist_data/train_episodes/habitat
valpath: ${root}/dist_data/val_episodes/habitat
datatype: ".mp4" # [.mp4, .png, .jpg]
doaug: "rctraj"

agent:
  _target_: vip.DistanceModel
  device: ${device}
  dino_model_name: dinov2-small
  lr: 3e-5
  output_dim: 1
  decoder_layers: 4
  dist_type: "linear"
  num_negatives: 0
  gamma: 0.98
  l2weight: 0.0001
  l1weight: 0.0001